### PR TITLE
Fix enums not quoted

### LINKED ISSUE #6: ImportError when pypika is also installed
When `pypika` and `pypika-tortoise` are both installed, both are installed within the same site-packages directory (see https://github.com/tortoise/pypika-tortoise/issues/5). This causes an `ImportError`, because `dialects/__init__.py`  is imported by upstream `pypika`'s `__init__.py`, instead of its own `dialects.py`:

```
File "/myproject/.venv/lib/python3.10/site-packages/tortoise/__init__.py", line 11, <module>
from pypika import Table
File "/myproject/.venv/lib/python3.10/site-packages/pypika/__init__.py", line 34, <module>
from pypika.dialects import (

dialects: <module 'pypika.dialects' from '/myproject/.venv/lib/python3.10/site-packages/pypika/dialects/__init__.py'>

ImportError:
cannot import name 'ClickHouseQuery' from 'pypika.dialects' (/myproject/.venv/lib/python3.10/site-packages/pypika/dialects/__init__.py)
```

Please rename this package. 

And if you've watched "the Fly", you'll know the disastrous consequences of merging two species 😉 .

### LINKED ISSUE #7: Enums not quoted
The original `pypika` has the bug kayak/pypika#560 which was fixed in kayak/pypika#576. `pypika-tortoise` has the same bug.

```python
import asyncio
from tortoise import fields, Tortoise, Model
from enum import Enum

class MyModel(Model):
    name = fields.TextField()

class MyEnum(str, Enum):
    A = "a"

async def do():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    qs = MyModel.filter(name=MyEnum.A)
    qs._make_query()
    print(qs.query)
    # expected   SELECT "id","name" FROM "mymodel" WHERE "name"='a'
    # actual     SELECT "id","name" FROM "mymodel" WHERE "name"=a

asyncio.run(do())
```

### PR DESCRIPTION
**Pull request by waketzheng**
Fixes #7 

Most code copied from https://github.com/kayak/pypika/pull/576
Then add test for datetime.time type, and run `poetry update` to upgrade dependencies, changed ruff command and config to fix warnings.
Add py.typed and pass mypy check.
Refactor utils and move Exceptions to a new file (exceptions.py)

### CODE REVIEW

**Comment by waketzheng** [comment]
@abondar Could you review this?

**Comment by henadzit** [comment]
Hey @waketzheng, thank you for PR!

Can you please provide a code snippet that uses Tortoise and exposes the bug? Maybe, a test case in Tortoise that will show the failing functionality.

It would be helpful if you create a PR to tortoise-orm where your version of `pypika-tortoise` is used, so we can see that CI passes. You can do it specifying your fork as a source for pypika-tortoise:
`pypika-tortoise = { git = "https://github.com/waketzheng/pypika-tortoise.git", branch = "fix-enums-not-quoted" }`

**Comment by waketzheng** [comment]
> Hey @waketzheng, thank you for PR!
> 
> Can you please provide a code snippet that uses Tortoise and exposes the bug? Maybe, a test case in Tortoise that will show the failing functionality.
> 
> It would be helpful if you create a PR to tortoise-orm where your version of `pypika-tortoise` is used, so we can see that CI passes. You can do it specifying your fork as a source for pypika-tortoise: `pypika-tortoise = { git = "https://github.com/waketzheng/pypika-tortoise.git", branch = "fix-enums-not-quoted" }`

@henadzit done. https://github.com/tortoise/tortoise-orm/pull/1776

**Review by abondar — APPROVED** [review]

**Comment by abondar** [comment]
@waketzheng Should I merge it and release? 

Or you would like to do it yourself?

**Comment by waketzheng** [comment]
> @waketzheng Should I merge it and release?
> 
> Or you would like to do it yourself?

Let me do it.

**Pull request merged**
